# -*- coding: utf-8 -*-
"""python aA-9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnsxIYAMkIu3v683Yv4g0SPeH5Q8s1BX
"""

#while loop

i=1
while(i<5):
  print("hey",i)
  i=i+1

i=1
sum=0
while(i<=15):
  sum=sum+i
  i=i+1
print(sum)

i=50
a=0
while(i<=24):
  sum
print(i,end="")

i=50
sum=0
while(i>=24):
  if(i%2==0):
    print("even",i)
  else:
    print("odd",i)
  i=i-1

i=2
count=0
while(i<=37):
  if(i%2==0):
    print("even",i)
  else:
    print("odd",i)
    count=count+1
  i=i+1
print("count",count)



i=3
total=0
while(i<=42):
  if(i%3==0):
    total=total+i
  i=i+1
print(total)

n=1345
while(n>0):
  rem=n%10
  n=n//10
  print("number =>",n, "reminder =>",rem)

n=1345
sum=0
while(n>0):
  rem=n%10
  n=n//10
  sum=sum+rem
print(sum)

n=153
original=n
sum=0
while(n>0):
  rem=n%10
  n=n//10
  sum=sum+rem**3
  print("number=>",n, "reminder=>",rem,rem**3)

print(sum)

